### ISSUE TITLE
Gosund SP1 (SP1-C_V2.4 20181101) is using https instead of http

### ISSUE THREAD

**Issue by toca2k** [ct-Open-Source/tuya-convert#213] opened 2019-06-07 22:03 UTC
Hi,

i'm trying to flash some Gosund SP1 (SP1-C_V2.4 20181101) . Looks like the Smartconfig part works fine. The device gets an IP, 10.42.42.32 in my case. As far as i understood the next step should be a http request to http://10.42.42.1. But in my case I see a connect to Port 443 via https :(

I tried to fake the https server with mitmproxy (sudo mitmproxy -R http://10.42.42.1 -p 443) but as I expected the Device is not accepting the certificate :(

Can anybody verify this?
Any ideas how to fix it?

**Comment by jfractalj** [comment] 2019-06-08 01:58
I have seen the same thing with the WP3. I don't think there has been a OTA fix released yet, but the device can probably be flashed manually.

**Comment by kueblc** [comment] 2019-07-02 19:48
Duplicate of #160 #166 #197 #199 #201

**Closed by kueblc** 2019-07-02 19:48 UTC

**Comment by BigDi** [comment] 2019-07-07 23:34
I tried it and works!

**Comment by wolfgangroller** [comment] 2019-07-26 12:25
> I tried it and works!

Please tell us what exactly you did, that it works now.

Thanks

**Comment by BigDi** [comment] 2019-07-27 08:06
I take the last two pull requests and merge it into the current release.
