### ISSUE TITLE
New devices - can not flash with 'tuya-convert'... Any solution?

### ISSUE THREAD

**Issue by darekhome** [ct-Open-Source/tuya-convert#879] opened 2020-12-21 08:03 UTC
I recently purchased few LED GU10 and E27 bulbs (they are on compatibility list), but they can not be flashed with 'tuya-convert'.
In hardware market (where I purchased them) they said that this is 'fresh' delivery from china producer...
So I assume - they have a new firmware, not allowing use the 'tuya-convert'.

Any solution to put a Tasmota firmware on the new devices?

The log is showing following:

```new client on port 443 from 10.42.42.16:65095
 
ID: 0242416f68626d64366147393149465231d8cb03f0594c021f20c1db770867464fef08e5151e38aa08e8b8bebecff198b4
 
PSK: f55c2d69f8e2c634625c25201d16a3a3cb73846c509a0a11ddba865dd4e2d2a1
 
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
 
new client on port 443 from 10.42.42.16:8154
```

**Comment by wormiedk** [comment] 2020-12-22 10:58
I have the same problem with a WOFEA garage door opener:

`ID: 0242416f68626d64366147393149465231bd52161255c1574a40ae03b9d1ab340e2eb6ae2e1db8bcc948d86ea50e3615d6
PSK: ee37f5e51086213c7049d30f2f811514f7a5c8ad8c255f6de72598f5a36f8f12
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
new client on port 443 from 10.42.42.30:61293`

**Comment by kueblc** [comment] 2020-12-22 16:10
Duplicate of #483

**Closed by kueblc** 2020-12-22 16:10 UTC
