### ISSUE TITLE
Smart bulb attempting flash but the moment smartpacket is sent the bulb goes solid

### ISSUE THREAD

**Issue by Icewolf0421** [ct-Open-Source/tuya-convert#693] opened 2020-07-09 01:05 UTC
As the title says I was attempting to flash two different smart bulbs but when the smartpackets start sending it goes solid out of ez pairing mode. Setup raspberry pi 3b+ which seems to be fine as I used it to flash three smart switches. Ant ideas would help.
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4893925/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4893926/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4893927/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4893928/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4893929/smarthack-mqtt.log)
Smart bulbs are Treatlife A19 8W 650lm RGBCCT Bulb and a derivative of Dogain 320lm RGBCCT Bulb

**Comment by datatype** [comment] 2020-07-10 19:14
exactly the same behaviour on a Novostella UT55509 13W 1300lm RGBCCT... 
OTA flashing of some Bakibo TB95 9W 1000lm still works like a charm.

**Comment by kueblc** [comment] 2020-07-10 19:30
Duplicate of #483, unfortunately this firmware is not supported

**Closed by kueblc** 2020-07-10 19:30 UTC
