### ISSUE TITLE
fake-registration-server.py - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dennislv** [ct-Open-Source/tuya-convert#169] opened 2019-04-10 15:34 UTC
Hi I'm trying to start by flashing a single light bulb and after many hours of fighting wifi devices/drivers, I was finally able to get past the access point created and the device connecting to it.  I'm running into an issue with fake-registration-server.py.  
pi@raspberrypi:~/tuya-convert/scripts $ ./fake-registration-server.py
Traceback (most recent call last):
  File "./fake-registration-server.py", line 9, in <module>
    import tornado.web
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1655
    async def _execute(
            ^
SyntaxError: invalid syntax

**Comment by dennislv** [comment] 2019-04-10 15:36
![2019-04-10_8-32-41](https://user-images.githubusercontent.com/4878314/55892765-c702f980-5b6b-11e9-9190-133f5e5abc03.png)

**Comment by kueblc** [comment] 2019-04-10 16:42
Duplicate of #144

**Closed** 2019-04-10 17:16 UTC
