### ISSUE TITLE
https tuya-convert issue

### ISSUE THREAD

**Issue by tjamesdp** [ct-Open-Source/tuya-convert#232] opened 2019-07-14 14:43 UTC
Question, 

Would it be possible to utilize sslstrip to downgrade the https session to http to allow updated devices from the manufacturer to still undergo the OTA tuya-convert process? Has anyone tested this?
https://github.com/moxie0/sslstrip

**Comment by kueblc** [comment] 2019-07-14 16:32
No, sorry

Duplicate of #223

**Closed by kueblc** 2019-07-14 16:32 UTC
