### ISSUE TITLE
could not establish sslpsk socket 

### ISSUE THREAD

**Issue by tobit6795** [ct-Open-Source/tuya-convert#791] opened 2020-10-11 16:39 UTC
hi again,

now im trying to flash a window sensor 

https://www.amazon.de/gp/product/B07Q8F46J4/r

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5361440/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5361441/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5361442/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5361443/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5361444/smarthack-wifi.log)

this is my current error (device is on 10.42.42.28)
```
new client on port 443 from 10.42.42.28:19752
ID: 0242416f68626d64366147393149465231ff8020cd96ed53806551061c8ead3a8f73d98bbfd629b2c24f6c0cef59e0d85c
PSK: 03d6823ed692c366ad935d8f9cb18666d46be20b52f76536a1800c8d1da9404e
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:852)
new client on port 443 from 10.42.42.21:47364
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:852)
```

**Comment by kueblc** [comment] 2020-10-11 18:22
Duplicate of #483. Unsupported firmware, see wiki for more information.

**Closed by kueblc** 2020-10-11 18:22 UTC
