### ISSUE TITLE
SSL error with new TB95 bulbs

### ISSUE THREAD

**Issue by iracigt** [ct-Open-Source/tuya-convert#549] opened 2020-02-21 15:04 UTC
I am unable to get a new (ordered last week) Slintinto TB95 to flash. The bulb was directly out of the box, and I had never used the Smart Life app.

Inspecting the psk log, I see the following error repeated many times:

```
new client on port 443 from 10.42.42.13:19278
ID: 0242416f68626d64366147393149465231f55eece48ad9ef7c5275ec8ef470bd5b1c5cdbcbce4bdf43109dc8b5d0cfc8d2
PSK: 749b48768c760bc1dd9bd0da112660c469f0d62827c80309a126f35094cdc8d8
could not establish sslpsk socket: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1056)
```

 I think the bulb joins the AP, but appears to have trouble establishing an SSL connection?

I disassembled the bulb, and there is definitely an ESP8285 inside. Board markings are "AJW-05_8285" and "190809VER:B".

I'm going attempt dumping the firmware before flashing over serial, but considering the very inconvenient placement of the UART test points, that will require desoldering the ESP module from the bulb.

This appears to be a different issue than #544, despite being the same model bulb.

Log Files:
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4236633/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4236634/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4236636/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4236637/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4236638/smarthack-wifi.log)

**Comment by kueblc** [comment] 2020-02-21 15:06
Duplicate of #483

**Closed by kueblc** 2020-02-21 15:06 UTC
