### ISSUE TITLE
Not possible to find my gosund sp111

### ISSUE THREAD

**Issue by MiguelESP89** [ct-Open-Source/tuya-convert#242] opened 2019-07-24 17:22 UTC
hey, 
I'm lost :D 
i want to flash my new gosund sp111. i installed all the things. my mobile phone is connceted to the wifi, the gosund is in pairing mode but my pi didn't find him. 

I have attached my logfiles. 

Thank you for your help

Miguel
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3428048/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3428049/smarthack-mqtt.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3428050/smarthack-web.log)
[smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/3428051/smarthack-smartconfig.log)

**Comment by kueblc** [comment] 2019-07-24 21:39
Duplicate of #216, unfortunately not compatible with `tuya-convert` at this time

**Closed by kueblc** 2019-07-24 21:39 UTC

**Comment by ibeerens** [comment] 2019-09-05 17:41
When will it be supported?
