### ISSUE TITLE
New firmware appears to have locked out tuya-convert

### ISSUE THREAD

**Issue by c0d3e** [ct-Open-Source/tuya-convert#245] opened 2019-07-31 23:45 UTC
I'm flashing some new gosund wp3's and have been getting indications that they have patched out tuya-converts flash vectors.

Instead of having a hard coded ip address of 10.42.42.42 the device picks up a DHCP address.  I bypassed this by resetting the DHCP pool to 10.42.42.41-42, connected my phone and then connected the smart plug.  The plug picks up the .42 address, then immediately gets a port 80 connection refused error.

This system was new from box, had not been connected to tuya.

**Comment by kueblc** [comment] 2019-08-01 00:07
Duplicate of #211 et al. Do not change the IP address, that simply lets the script know if the flash succeeded, when it did not.

**Closed by kueblc** 2019-08-01 00:07 UTC
