### ISSUE TITLE
Convert tuya TB95 light bulb (bakibo)

### ISSUE THREAD

**Issue by AlessandroPerazzetta** [ct-Open-Source/tuya-convert#600] opened 2020-04-30 08:19 UTC
In an attempt to convert a bakibo light bulb (rgb) I get "Device did not appear with the intermediate firmware".
Installed tuya-convert on raspberry, start_flash starts correctly (vtrust wifi ap visible) and it seems that the light is trying to upgrade.
The card on board is an esp8285, with the following wording: ajw-05_8285.

Log files:
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4556951/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4556952/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4556953/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4556954/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4556955/smarthack-wifi.log)

So I tried connecting a serial on the pads and from console you can see the following handshake:
[debug.log](https://github.com/ct-Open-Source/tuya-convert/files/4557015/debug.log)

Failing the ota update I tried to upgrade to Tasmota by connecting rx / tx on the pads under the board, i saved the original firmware with esptool, it is necessary to enter flash mode by bridging the pad (GPIO0 ???) and GND, upgrade successful.
![2020-04-30 10 05 14](https://user-images.githubusercontent.com/482310/80688089-95890300-8acb-11ea-8b69-b5030d3052e4.png)

**Comment by kueblc** [comment] 2020-04-30 14:33
Duplicate of #483

**Closed by kueblc** 2020-04-30 14:33 UTC
