### ISSUE TITLE
Failed to flash GIRIER Smart Plug with monitoring JR-PM01

### ISSUE THREAD

**Issue by BugsonPL** [ct-Open-Source/tuya-convert#798] opened 2020-10-16 15:21 UTC
Main and MCU Tuya version 1.1.7

Connects to AP but fails to flash.

I have flashed with my setup about 10 other devices.

I attache the logs.
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5392552/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5392553/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5392554/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5392555/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5392556/smarthack-mqtt.log)

**Comment by kueblc** [comment] 2020-10-16 22:36
Unsupported firmware. Duplicate of #483.

**Closed by kueblc** 2020-10-16 22:36 UTC
