### ISSUE TITLE
Teckin SP22: could not establish sslpsk socket

### ISSUE THREAD

**Issue by dekiesel** [ct-Open-Source/tuya-convert#447] opened 2019-12-10 12:09 UTC
Hi,

I am trying to flash 4 Teckin SP22 that I got today from amazon.de.

I updated my local git repo and rerun install_prereq.sh.

I then started start_flash.sh, connected to the AP, made sure that the LED on the SP22 was blinking blue and then hit Enter.

The screen output: 

```
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword          
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
...........
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Stopping smart config
Do you want to try flashing another device? [y/N] N
Exiting...
```

I found this error in smarthack-psk.log
```
PSK: 03fa10a357626f2bdbc2a1db48fcfd3902deac10a1cf6645fba3b1c2bec85540
('could not establish sslpsk socket:', SSLError(1, u'[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:727)'))
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 111, in <module>
    main()
  File "./psk-frontend.py", line 104, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt
```

I don't know what firmware the sockets are on because I haven't connected them to the app yet.

Any ideas what I am doing wrong?

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3944758/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/3944759/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/3944760/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3944761/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3944762/smarthack-wifi.log)

**Comment by kueblc** [comment] 2019-12-10 12:46
From your web log:
```
WARNING: it appears this device does not use an ESP82xx and therefore cannot install ESP based firmware
```
Teckin has switched to new hardware. Unfortunately neither tuya-convert nor ESP based firmwares like Tasmota/Espurna will work here.

Duplicate of #269 #310 #321 #327 #341 #364 #370 #380 #391 #425 #438

**Closed by kueblc** 2019-12-10 12:46 UTC
