### ISSUE TITLE
RGB Bulb Flashing not working, stuck at sending smartconfig

### ISSUE THREAD

**Issue by Atlas-2005** [ct-Open-Source/tuya-convert#799] opened 2020-10-16 17:33 UTC
Hello,
I am trying to flash a RGB blub from globe suite with firmware version 1.15.

Fallowing the guide on a RPI 3b+ i get to the AP section and have tried connecting with a iPhone and Ipad, then I put the bulb in easy config and start the process the light stops blinking but the terminal doesn't ever do anything else. Logs Below, Thanks
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/5393365/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/5393366/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/5393367/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/5393368/smarthack-wifi.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/5393369/smarthack-mqtt.log)

**Comment by kueblc** [comment] 2020-10-16 22:37
Unsupported firmware. Duplicate of #483.

**Closed by kueblc** 2020-10-16 22:37 UTC
