### ISSUE TITLE
Problem flashing LSC Motion sensor

### ISSUE THREAD

**Issue by JochemHam** [ct-Open-Source/tuya-convert#422] opened 2019-11-27 09:20 UTC
Hi, I got one of the LSC motion sensors and tried flashing it with tuya-convert.

I doens't seem to be working. I get the follow message:

### IMPORTANT
1. Connect any other device (a smartphone or something) to the WIFI vtrust-flash
   This step is IMPORTANT otherwise the smartconfig may not work!
2. Put your IoT device in autoconfig/smartconfig/pairing mode (LED will blink fast). This is usually done by pressing and holding the primary button of the device
   Make sure nothing else is plugged into your IoT device while attempting to flash.
3. Press ENTER to continue

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Auto retry in 2s. ................................................................................................................
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N] y

I read before that it may have something to do with the sleepmode of this device. But it seems to be something else here.

Anybody got any ideas?

These are my logs:
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3896044/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/3896045/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/3896046/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3896047/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3896048/smarthack-wifi.log)

**Comment by kueblc** [comment] 2019-11-27 14:37
Duplicate of #135 #355 #383 #384 #390 

The reason we can't flash these is that the device does not stay connected to wifi once it receives the dynamic config. Please keep the discussion in #135. If you are able to create a network capture please share it there, it might help find another way to keep the device connected long enough to upgrade.

**Closed by kueblc** 2019-11-27 14:37 UTC

**Comment by DenDeze** [comment] 2024-09-19 13:11
https://homehacker.nl/flashing-lsc-sensors/
