### ISSUE TITLE
DIGOO DG-SP01

### ISSUE THREAD

**Issue by fragolinux** [ct-Open-Source/tuya-convert#118] opened 2019-03-02 17:39 UTC
today i flashed 3 devices, so i know the procedure, but can't succeed in flashing the one in title...
attached logs... device seems connecting to rpi AP as it stops blinking led but after about 10 minutes is still there, waiting to do don't know what...
[smarthack-smartconfig.log](https://github.com/ct-Open-Source/tuya-convert/files/2922352/smarthack-smartconfig.log)
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/2922353/smarthack-mqtt.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/2922354/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/2922355/smarthack-wifi.log)

**Comment by kueblc** [comment] 2019-03-02 19:23
Out of curiosity, which devices flashed successfully?

It looks like the pairing process completed successfully and the upgrade message was sent but the device did not fetch the firmware file. This indicates to me that the format of the response was not as expected.

I would like to track this down but I cannot reproduce this issue so any information you can provide will be very helpful.

**Comment by fragolinux** [comment] 2019-03-02 19:53
tell me if we can chat on discord tomorrow and i'll do any test you ask...
these are the devices i flashed:

https://github.com/arendst/Sonoff-Tasmota/wiki/BlitzWolf-SHP6
https://blakadder.github.io/templates/houzetek-swa1.html
https://blakadder.github.io/templates/alfawise-pe1004.html

latest 2 are their templates i published after configuring them

an other device i couldn't flash is this, but then i opened it and saw it has a mediatek chip inside, not esp8266... https://www.amazon.it/Interruttore-spegnimento-elettronico-telecomando-elettrodomestici/dp/B01N11AW60

**Comment by fragolinux** [comment] 2019-03-03 20:25
succeeded to flash today, don't know what was different... i think something with dhcp leases, if you do many devices at once... i started this evening and it just worked... i flashed an Emylo switch, too, no problems... thanks!
![image](https://user-images.githubusercontent.com/21192010/53701174-b340d680-3dfa-11e9-9785-878d0a550c76.png)

**Comment by kueblc** [comment] 2019-03-03 20:41
OK perfect, glad it worked out! You can close this issue if you are satisfied.

**Closed** 2019-03-03 21:08 UTC

**Comment by Selters** [comment] 2019-05-28 20:10
> succeeded to flash today, don't know what was different.



Hi @fragolinux ,

Could you please let me know how to open the case of DIGOO DG-SP01?
Are there any hidden screws?

Thanks in advance!

**Comment by fragolinux** [comment] 2019-05-29 06:55
> > succeeded to flash today, don't know what was different.
> 
> Hi @fragolinux ,
> 
> Could you please let me know how to open the case of DIGOO DG-SP01?
> Are there any hidden screws?
> 
> Thanks in advance!

ehm, as we are discussing on how to flash them without opening, obviously i never opened it, flashed via tuya-convert...

**Comment by Selters** [comment] 2019-05-29 19:13
> how to flash them without opening

Thanks!
This was the missing part ;)

**Comment by MrMennens** [comment] 2019-06-09 10:52
Did you flash a specific firmware? Or just the normal tasmota?
Wondering if you can choose to turn on/off the socket, light & the 2 usb ports

**Comment by fragolinux** [comment] 2019-06-10 07:09
flash 6.5.0 based on sdk 2.3.0, then go on blakadder site and search for the template to use, done

**Comment by MrMennens** [comment] 2019-06-10 20:21
thnx for the reply,

can't seem to get it flashed with tuya-convert..
putty only shows ..........................
led of the digoo stopped blinking after a while..

**Comment by MrMennens** [comment] 2019-06-25 09:03
Tried a couple different pi's,
Tried a couple of new installs
still nothing, could it be the firmware of the Digoo DG-SP01 is just not working with the tuya convert anymore?
If it doesn't work i'm checking out to see if i can make it work with a IFTTT workaround...

**Comment by zehrer** [comment] 2021-02-01 20:38
The Template Settings Sems not working well. E.g. the status led is on when the light is on. Somebody have the same issue?
