### ISSUE TITLE
Device does not appear with the intermediate firmware.

### ISSUE THREAD

**Issue by GijsTimmers** [ct-Open-Source/tuya-convert#542] opened 2020-02-16 14:50 UTC
Running commit 31856ada24a1e951b4da849bff2ed056f544c51b on an Ubuntu 19.10 live usb.
Trying to flash a LSC movement sensor (https://www.mikrocontroller.net/attachment/426891/Bauteilseite1_klein.jpg)

It does not seem to flash the firmware. It starts the web server fine, I can connect to it, SmartConfig completes and then the device does not appear with the intermediate firmware.

All help is appreciated.

Logs:

```
root@ubuntu:/home/ubuntu/tuya-convert/scripts# cat smarthack-mqtt.log 
1581864064: mosquitto version 1.6.6 starting
1581864064: Using default config.
1581864064: Opening ipv4 listen socket on port 1883.
1581864064: Opening ipv6 listen socket on port 1883.
1581864101: New connection from 10.42.42.1 on port 1883.
1581864101: New client connected from 10.42.42.1 as 038880662462ab111c2b (p1, c1, k60, u'038880662462ab111c2b').
1581864101: No will message specified.
1581864101: Sending CONNACK to 038880662462ab111c2b (0, 0)
1581864101: Received SUBSCRIBE from 038880662462ab111c2b
1581864101:     smart/device/in/038880662462ab111c2b (QoS 0)
1581864101: 038880662462ab111c2b 0 smart/device/in/038880662462ab111c2b
1581864101: Sending SUBACK to 038880662462ab111c2b
1581864111: New connection from 127.0.0.1 on port 1883.
1581864111: New client connected from 127.0.0.1 as auto-55783521-FDFF-89B1-1C7B-072AF80ABF1B (p2, c1, k60).
1581864111: No will message specified.
1581864111: Sending CONNACK to auto-55783521-FDFF-89B1-1C7B-072AF80ABF1B (0, 0)
1581864111: Received PUBLISH from auto-55783521-FDFF-89B1-1C7B-072AF80ABF1B (d0, q0, r0, m0, 'smart/device/in/038880662462ab111c2b', ... (111 bytes))
1581864111: Sending PUBLISH to 038880662462ab111c2b (d0, q0, r0, m0, 'smart/device/in/038880662462ab111c2b', ... (111 bytes))
1581864111: Received DISCONNECT from auto-55783521-FDFF-89B1-1C7B-072AF80ABF1B
1581864111: Client auto-55783521-FDFF-89B1-1C7B-072AF80ABF1B disconnected.
1581864192: Client 038880662462ab111c2b has exceeded timeout, disconnecting.
1581864225: New connection from 10.42.42.1 on port 1883.
1581864225: New client connected from 10.42.42.1 as 038880662462ab111c2b (p1, c1, k60, u'038880662462ab111c2b').
1581864225: No will message specified.
1581864225: Sending CONNACK to 038880662462ab111c2b (0, 0)
1581864225: Received SUBSCRIBE from 038880662462ab111c2b
1581864225:     smart/device/in/038880662462ab111c2b (QoS 0)
1581864225: 038880662462ab111c2b 0 smart/device/in/038880662462ab111c2b
1581864225: Sending SUBACK to 038880662462ab111c2b
1581864235: New connection from 127.0.0.1 on port 1883.
1581864235: New client connected from 127.0.0.1 as auto-9C5F5CEE-B1FE-9421-D441-EA9EF89A2892 (p2, c1, k60).
1581864235: No will message specified.
1581864235: Sending CONNACK to auto-9C5F5CEE-B1FE-9421-D441-EA9EF89A2892 (0, 0)
1581864235: Received PUBLISH from auto-9C5F5CEE-B1FE-9421-D441-EA9EF89A2892 (d0, q0, r0, m0, 'smart/device/in/038880662462ab111c2b', ... (111 bytes))
1581864235: Sending PUBLISH to 038880662462ab111c2b (d0, q0, r0, m0, 'smart/device/in/038880662462ab111c2b', ... (111 bytes))
1581864235: Received DISCONNECT from auto-9C5F5CEE-B1FE-9421-D441-EA9EF89A2892
1581864235: Client auto-9C5F5CEE-B1FE-9421-D441-EA9EF89A2892 disconnected.
1581864316: Client 038880662462ab111c2b has exceeded timeout, disconnecting.
1581864318: New connection from 10.42.42.1 on port 1883.
1581864318: New client connected from 10.42.42.1 as 038880662462ab111c2b (p1, c1, k60, u'038880662462ab111c2b').
1581864318: No will message specified.
1581864318: Sending CONNACK to 038880662462ab111c2b (0, 0)
1581864318: Received SUBSCRIBE from 038880662462ab111c2b
1581864318:     smart/device/in/038880662462ab111c2b (QoS 0)
1581864318: 038880662462ab111c2b 0 smart/device/in/038880662462ab111c2b
1581864318: Sending SUBACK to 038880662462ab111c2b
^C1581864320: Socket error on client 038880662462ab111c2b, disconnecting.
1581864320: mosquitto version 1.6.6 terminating
```

```
root@ubuntu:/home/ubuntu/tuya-convert/scripts# cat smarthack-psk.log 
new client on port 443 from 10.42.42.39:46960
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:46962
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:46964
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:46974
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:46978
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.34:6456
ID: 0142416f68626d64366147393149465231b94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
PSK: e83bae9f159f8a02d7ce968042d1cb99c7a3287e4d5ef6e083c0c4c9c0664128
new client on port 443 from 10.42.42.34:5123
ID: 0142416f68626d64366147393149465231b94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
PSK: e83bae9f159f8a02d7ce968042d1cb99c7a3287e4d5ef6e083c0c4c9c0664128
new client on port 8886 from 10.42.42.34:5302
ID: 0142416f68626d64366147393149465231b94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
PSK: e83bae9f159f8a02d7ce968042d1cb99c7a3287e4d5ef6e083c0c4c9c0664128
new client on port 443 from 10.42.42.34:10579
ID: 0142416f683f3f3f3f3f3f3f3f3f3f3f3fb94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
Prefix: b'BAoh????????????'
PSK: 56c22cf7897207c4709797f5c04c5bcf7755a154bd804cf390735e1e68378560
new client on port 443 from 10.42.42.39:46984
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:46990
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:46996
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 8886 from 10.42.42.34:13634
[Errno 104] Connection reset by peer
new client on port 443 from 10.42.42.34:4114
ID: 0142416f68626d64366147393149465231b94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
PSK: e83bae9f159f8a02d7ce968042d1cb99c7a3287e4d5ef6e083c0c4c9c0664128
new client on port 443 from 10.42.42.34:24439
ID: 0142416f68626d64366147393149465231b94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
PSK: e83bae9f159f8a02d7ce968042d1cb99c7a3287e4d5ef6e083c0c4c9c0664128
new client on port 8886 from 10.42.42.34:9798
ID: 0142416f68626d64366147393149465231b94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
PSK: e83bae9f159f8a02d7ce968042d1cb99c7a3287e4d5ef6e083c0c4c9c0664128
new client on port 443 from 10.42.42.34:11953
ID: 0142416f68626d64366147393149465231b94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
PSK: e83bae9f159f8a02d7ce968042d1cb99c7a3287e4d5ef6e083c0c4c9c0664128
new client on port 443 from 10.42.42.39:47010
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 443 from 10.42.42.39:47012
could not establish sslpsk socket: [SSL: NO_SHARED_CIPHER] no shared cipher (_ssl.c:1076)
don't panic this is probably just your phone!
new client on port 8886 from 10.42.42.34:33074
ID: 0142416f68626d64366147393149465231b94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
PSK: e83bae9f159f8a02d7ce968042d1cb99c7a3287e4d5ef6e083c0c4c9c0664128
new client on port 443 from 10.42.42.34:17068
ID: 0142416f68626d64366147393149465231b94f046466691fff7fcefe95153588935f272631b47c414295878141533faaec27
PSK: e83bae9f159f8a02d7ce968042d1cb99c7a3287e4d5ef6e083c0c4c9c0664128
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 113, in <module>
    main()
  File "./psk-frontend.py", line 106, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt
```

```
root@ubuntu:/home/ubuntu/tuya-convert/scripts# cat smarthack-udp.log 
Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
```

```
root@ubuntu:/home/ubuntu/tuya-convert/scripts# cat smarthack-web.log 
Listening on 10.42.42.1:80
[I 200216 14:41:07 web:2246] 302 GET /generate_204 (10.42.42.39) 1.60ms
[I 200216 14:41:07 web:2246] 302 GET /generate_204 (10.42.42.39) 1.00ms
[I 200216 14:41:09 web:2246] 302 GET /generate_204 (10.42.42.39) 0.96ms
[I 200216 14:41:09 web:2246] 302 GET /generate_204 (10.42.42.39) 0.98ms
[I 200216 14:41:09 web:2246] 200 GET / (10.42.42.39) 1.69ms

GET /gw.json?a=s.gw.token.get&et=1&gwId=038880662462ab111c2b&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":0,"source":"ap","path":"multicast"}}&t=3&v=3.0&sign=7a18f1bd9173251d86644c1155a12726
Host: a3.tuyaus.com
User-Agent: ESP8266SDK
Connection: keep-alive

Answer s.gw.token.get
reply {"t":1581864100,"e":false,"success":true,"result":{"gwApiUrl":"http://10.42.42.1/gw.json","stdTimeZone":"-05:00","mqttRanges":"","timeZone":"-05:00","httpsPSKUrl":"https://10.42.42.1/gw.json","mediaMqttUrl":"10.42.42.1","gwMqttUrl":"10.42.42.1","dstIntervals":[],"mqttsUrl":"10.42.42.1","mqttsPSKUrl":"10.42.42.1","mediaMqttsUrl":"10.42.42.1","aispeech":"10.42.42.1"}}
[I 200216 14:41:40 web:2246] 200 GET /gw.json?a=s.gw.token.get&et=1&gwId=038880662462ab111c2b&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":0,"source":"ap","path":"multicast"}}&t=3&v=3.0&sign=7a18f1bd9173251d86644c1155a12726 (10.42.42.1) 16.03ms

POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=038880662462ab111c2b&other={"token":"00000000"}&t=3&v=3.0&sign=129f0bf7999b1e5a5e7681fb85c2ac77
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 549

payload AE88E2892452EDCA75C90758BEE49B657707B8BAD956CEA14897CFC590792F478B17E0D836D3E2E8553C1F84354BC250E045E117BFFFAB6D4F920F161F7AA78AB52CC746D81D40208CF914205CAA917FF97DE59D365F6B4527C8EE9DA1147EB6AD099401ED40C52F730A5924DCD34A4364373555647D000321EB55D29D916070F7D844D842B47B069C08FC8751874EEF359EB94F7B28918AB501FAA2753B922CC452080D9B85B7E37AA8BCE1F466F502FAB78256AE9578921A74FAB0EDA4BD8E356AC5919EEE49C2603CC6AF38CD5EB5A4081F00A3738D9462DFA3AABC5F104FB74A75D46AA08343782FF5EE2A436FE4BF4B367AB473F78379CF015B138E5C33729C6857C7494CB1A7BECE4D62E741AF
Answer s.gw.dev.pk.active
reply {"t":1581864101,"e":false,"success":true,"result":{"schema":"[{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"},{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"}]","uid":"00000000000000000000","devEtag":"0000000000","secKey":"0000000000000000","schemaId":"0000000000","localKey":"0000000000000000"}}
TRIGGER UPGRADE IN 10 SECONDS
[I 200216 14:41:41 web:2246] 200 POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=038880662462ab111c2b&other={"token":"00000000"}&t=3&v=3.0&sign=129f0bf7999b1e5a5e7681fb85c2ac77 (10.42.42.1) 16.19ms

POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=038880662462ab111c2b&t=4&v=1.0&sign=720b29dfd78c72ea7d98b6c25fd73dd6
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 0

Answer tuya.device.dynamic.config.get
reply {"result":"fn8oBaEAaJe3I+enO7OkYdd0LkD9WHnY6k8vmvctrJZ79OqzO0IbzlVUd0tTKMnF9F2VBmqNqTqJcWuiX4YubMiKKrHRIXgDq5V5F8gQkRm7mevrGF2WUpAllBDW/Q5l","t":1581864101,"sign":"cb4ebaddc3cb0a2c"}
[I 200216 14:41:41 web:2246] 200 POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=038880662462ab111c2b&t=4&v=1.0&sign=720b29dfd78c72ea7d98b6c25fd73dd6 (10.42.42.1) 1.83ms
encoding {"data":{"gwId":"038880662462ab111c2b"},"protocol":15,"s":"1523715","t":"1581864111"} using protocol 2.2
b"2.2\xb03i\x7f86411127\xb7\x98\xa7\x08\xc0\xc7\xa5\xc2JB\x9c_9\xed\x91m\x07'\x00\x92\x15{j^BCV\xa7\xf5\xb7p\x80Z\xd2\xa3\xd0\xd87]9z\x15-\xef\xdf\x19\xaeu\x91\xfa\xef\xd4\xa8\xffL\x1a\xef\x01\r\x8e\xbd\xf5EL\xc4\x8f\x18\xa2\x86\xceFj\xb4\xe1\xf2 \x94\x9e\x9d\x82\x95S}\xe3\xa8\xe9\xa0c\x16\xa5\x8b\xa9`\x0e\xdf\xfe"
[I 200216 14:42:13 web:2246] 302 GET /generate_204 (10.42.42.39) 0.92ms

GET /gw.json?a=s.gw.token.get&et=1&gwId=038880662462ab111c2b&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":0,"source":"ap","path":"multicast"}}&t=4&v=3.0&sign=189cc10bf213ccd7bb2f2edb80a24e7c
Host: a3.tuyaus.com
User-Agent: ESP8266SDK
Connection: keep-alive

Answer s.gw.token.get
reply {"t":1581864224,"e":false,"success":true,"result":{"gwApiUrl":"http://10.42.42.1/gw.json","stdTimeZone":"-05:00","mqttRanges":"","timeZone":"-05:00","httpsPSKUrl":"https://10.42.42.1/gw.json","mediaMqttUrl":"10.42.42.1","gwMqttUrl":"10.42.42.1","dstIntervals":[],"mqttsUrl":"10.42.42.1","mqttsPSKUrl":"10.42.42.1","mediaMqttsUrl":"10.42.42.1","aispeech":"10.42.42.1"}}
[I 200216 14:43:44 web:2246] 200 GET /gw.json?a=s.gw.token.get&et=1&gwId=038880662462ab111c2b&other={"token":"00000000","region":"US","tlinkStat":{"configure":"smartconfig","time":0,"source":"ap","path":"multicast"}}&t=4&v=3.0&sign=189cc10bf213ccd7bb2f2edb80a24e7c (10.42.42.1) 15.68ms

POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=038880662462ab111c2b&other={"token":"00000000"}&t=5&v=3.0&sign=19bf89ee23f41c7c651d4c778fcfd8a1
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 549

payload AE88E2892452EDCA75C90758BEE49B657707B8BAD956CEA14897CFC590792F478B17E0D836D3E2E8553C1F84354BC250E045E117BFFFAB6D4F920F161F7AA78AB52CC746D81D40208CF914205CAA917FF97DE59D365F6B4527C8EE9DA1147EB6AD099401ED40C52F730A5924DCD34A4364373555647D000321EB55D29D916070F7D844D842B47B069C08FC8751874EEF359EB94F7B28918AB501FAA2753B922CC452080D9B85B7E37AA8BCE1F466F502FAB78256AE9578921A74FAB0EDA4BD8E356AC5919EEE49C2603CC6AF38CD5EB5A4081F00A3738D9462DFA3AABC5F104FB74A75D46AA08343782FF5EE2A436FE4BF4B367AB473F78379CF015B138E5C33729C6857C7494CB1A7BECE4D62E741AF
Answer s.gw.dev.pk.active
reply {"t":1581864225,"e":false,"success":true,"result":{"schema":"[{\"mode\":\"rw\",\"property\":{\"type\":\"bool\"},\"id\":1,\"type\":\"obj\"}]","uid":"00000000000000000000","devEtag":"0000000000","secKey":"0000000000000000","schemaId":"0000000000","localKey":"0000000000000000"}}
TRIGGER UPGRADE IN 10 SECONDS
[I 200216 14:43:45 web:2246] 200 POST /gw.json?a=s.gw.dev.pk.active&et=1&gwId=038880662462ab111c2b&other={"token":"00000000"}&t=5&v=3.0&sign=19bf89ee23f41c7c651d4c778fcfd8a1 (10.42.42.1) 13.36ms

POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=038880662462ab111c2b&t=5&v=1.0&sign=cde96037431ed8cf0c57f5c476d4f15e
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 0

Answer tuya.device.dynamic.config.get
reply {"result":"fn8oBaEAaJe3I+enO7OkYdd0LkD9WHnY6k8vmvctrJbQCxh4judzUSo0b/mGpQna9F2VBmqNqTqJcWuiX4YubKp8gKIh2m7gghAuFgB4mkG7mevrGF2WUpAllBDW/Q5l","t":1581864225,"sign":"5cbc84616e96dd76"}
[I 200216 14:43:45 web:2246] 200 POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=038880662462ab111c2b&t=5&v=1.0&sign=cde96037431ed8cf0c57f5c476d4f15e (10.42.42.1) 1.61ms
encoding {"data":{"gwId":"038880662462ab111c2b"},"protocol":15,"s":"1523715","t":"1581864235"} using protocol 2.2
b"2.2\xe5\x9c\xeb)86423542\xb7\x98\xa7\x08\xc0\xc7\xa5\xc2JB\x9c_9\xed\x91m\x07'\x00\x92\x15{j^BCV\xa7\xf5\xb7p\x80Z\xd2\xa3\xd0\xd87]9z\x15-\xef\xdf\x19\xaeu\x91\xfa\xef\xd4\xa8\xffL\x1a\xef\x01\r\x8e\xbd\xf5EL\xc4\x8f\x18\xa2\x86\xceFj\xb4\xe1\xf2 \x94\x9e\x9d\x82\x91\xf5:\xd9\xa4\xb1\xad\xbf\xbcZN\xb0\xf5S\x15\xa1"

POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=038880662462ab111c2b&t=2&v=1.0&sign=49a18a8d146d76628df5adcf12d6729a
Host: 10.42.42.1
User-Agent: ESP8266SDK
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 0

Answer tuya.device.dynamic.config.get
reply {"result":"fn8oBaEAaJe3I+enO7OkYdd0LkD9WHnY6k8vmvctrJYp+ePxNMsX4itndW3MwLoS9F2VBmqNqTqJcWuiX4YubABcg76uhHshf1zz+g45DB+7mevrGF2WUpAllBDW/Q5l","t":1581864318,"sign":"e382285bfe2069fb"}
[I 200216 14:45:18 web:2246] 200 POST /gw.json?a=tuya.device.dynamic.config.get&et=1&gwId=038880662462ab111c2b&t=2&v=1.0&sign=49a18a8d146d76628df5adcf12d6729a (10.42.42.1) 1.61ms
^CReceived SIGINT, exiting...
```

```
root@ubuntu:/home/ubuntu/tuya-convert/scripts# cat smarthack-wifi.log 
System info
===========
31856ad
Linux ubuntu 5.3.0-18-generic #19-Ubuntu SMP Tue Oct 8 20:14:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
OpenSSL 1.1.1c  28 May 2019
Dnsmasq version 2.80  Copyright (c) 2000-2018 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
hostapd v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
Python 3.7.5
===========
Attempting to stop wpa_supplicant
Stopping NetworkManager...
Configuring AP interface...
RTNETLINK answers: File exists
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlo1...
Configuration file: /dev/stdin
Using interface wlo1 with hwaddr 98:2c:bc:ab:54:5a and ssid "vtrust-flash"
wlo1: interface state UNINITIALIZED->ENABLED
wlo1: AP-ENABLED 
wlo1: AP-STA-CONNECTED 72:f0:0c:e2:6e:2a
wlo1: AP-STA-CONNECTED 24:62:ab:11:1c:2b
wlo1: AP-STA-DISCONNECTED 24:62:ab:11:1c:2b
wlo1: AP-STA-CONNECTED 24:62:ab:11:1c:2b
wlo1: AP-STA-DISCONNECTED 24:62:ab:11:1c:2b
wlo1: AP-STA-CONNECTED 24:62:ab:11:1c:2b
wlo1: AP-STA-DISCONNECTED 24:62:ab:11:1c:2b
wlo1: AP-STA-CONNECTED 24:62:ab:11:1c:2b
wlo1: interface state ENABLED->DISABLED
wlo1: AP-STA-DISCONNECTED 24:62:ab:11:1c:2b
wlo1: AP-STA-DISCONNECTED 72:f0:0c:e2:6e:2a
wlo1: AP-DISABLED 
wlo1: CTRL-EVENT-TERMINATING 
nl80211: deinit ifname=wlo1 disabled_11b_rates=0
AP closed
Stopping DNSMASQ server...
Restarting NetworkManager...
```

**Comment by The-May** [comment] 2020-02-16 15:35
Same issue here with a pi3 on the latest raspbian buster version 2020-02-05 and 2019-04-08 raspbian stretch.

**Comment by kueblc** [comment] 2020-02-16 15:35
Duplicate of #135. These devices have a secondary MCU that powers down the ESP until there is data to send, so it is a tricky matter to keep the device online long enough to flash.

**Closed by kueblc** 2020-02-16 15:35 UTC
