### ISSUE TITLE
Not able to send SmartConfig Packets

### ISSUE THREAD

**Issue by cdk222** [ct-Open-Source/tuya-convert#648] opened 2020-05-29 17:15 UTC
Device: Arlec 5m LED Strip
Version: Tuya-convert 2.4.3

Hi 

Firstly thank you for your work with the Tuya-convert. 
I am having a nightmare trying to flash my Arlec LED Light strip. I have seen on other sites that others have been able to do so successfully with tuya-connect but not for me. I successfully connected a laptop, IOS, Android (tried all 3) to the Vtrust wifi and can get the LED strip into pair mode, everything else loads successfully but it just does not appear to connect. The LED will actually stop blinking which i take to indicate that it is trying to pair/connect. I had exactly the same issue with a lightbulb (Brilliant brand) which others have been able to use tuya-convert.....im thinking its my linux setup and potentially something blocking the pairing?????  I have looked through the Issues page and have tried the solutions suggested for others without success. I get the following message:

-----------------------------------------------------------------------------
tuya-convert v2.4.3
Checking for network interface wlan0... Found.
Checking UDP port 53... Available.
Checking UDP port 67... Available.
Checking TCP port 80... Available.
Checking TCP port 443... Available.
Checking UDP port 6666... Available.
Checking UDP port 6667... Available.
Checking TCP port 1883... Available.
Checking TCP port 8886... Available.
sudo: ufw: command not found
======================================================
  Starting AP in a screen
  Stopping any apache web server
  Starting web server in a screen
  Starting Mosquitto in a screen
  Starting PSK frontend in a screen
  Starting Tuya Discovery in a screen

Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID vtrust-flash
Sending wifiPassword
Sending token 00000000
Sending secret 0101
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
................
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Stopping smart config
Do you want to flash another device? [y/N]
----------------------------------------------------------------------------------

[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/4703190/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/4703191/smarthack-psk.log)
[smarthack-udp.log](https://github.com/ct-Open-Source/tuya-convert/files/4703192/smarthack-udp.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/4703193/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/4703194/smarthack-wifi.log)

**Comment by kueblc** [comment] 2020-05-29 17:20
Duplicate of #483

**Closed by kueblc** 2020-05-29 17:20 UTC
