### ISSUE TITLE
Trying to flash Globe Tuya bulb and getting errors

### ISSUE THREAD

**Issue by shep99** [ct-Open-Source/tuya-convert#372] opened 2019-11-02 18:21 UTC
I'm trying to flash "Globe" bulb Tuya, and getting the following errors. I'm using an RPI 3 B+:

======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
................
SmartConfig complete.
Resending SmartConfig Packets
./start_flash.sh: line 133:  3465 Terminated              ./smartconfig/main.py
[smarthack-mqtt.log](https://github.com/ct-Open-Source/tuya-convert/files/3800817/smarthack-mqtt.log)
[smarthack-psk.log](https://github.com/ct-Open-Source/tuya-convert/files/3800818/smarthack-psk.log)
[smarthack-web.log](https://github.com/ct-Open-Source/tuya-convert/files/3800819/smarthack-web.log)
[smarthack-wifi.log](https://github.com/ct-Open-Source/tuya-convert/files/3800820/smarthack-wifi.log)

**Comment by kueblc** [comment] 2019-11-02 20:10
Duplicate of #354; you can try implementing the fix yourself or wait a few days and we'll have it available

**Closed by kueblc** 2019-11-02 20:10 UTC

**Comment by shep99** [comment] 2019-11-08 01:46
Thank you!
